version: '3.9'
services:
  mongo:
    image: mongo
    container_name: transact-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongo:27017/
    depends_on:
      - mongo

#  transact-app:
#    build: ./
#    image: transact-app
#    command: -configFile /config/local.yaml
#    environment:
#      - MONGODB_URL=mongodb://mongodb:27017/test
#    ports:
#      - '8080:8080'
#    depends_on:
#      - mongo
#    volumes:
#      - .:/src
#      - ./config/local.yaml:/config/local.yaml
#    networks:
#      - transact-network

networks:
  transact-network:
    driver: bridge