// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Create implements create operation.
	//
	// Create a new transaction.
	//
	// POST /create
	Create(ctx context.Context, req *CreateTransactionRequest) (*CreateTransactionResponse, error)
	// Get implements get operation.
	//
	// Get a new transaction in a specific currency.
	//
	// GET /get
	Get(ctx context.Context, req *GetTransactionRequest) (*GetTransactionResponse, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
